# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38373dad1c13f7f85de0d98c989b3298de358383c3514a800b778c4c5690a6a91f21420c993fea44c55db3e9f6522f606111db182f5f727332f320b77a348106

test:
  secret_key_base: 05054a85cd4491fbf4a88764c08922ce80b5ef62071af433e9bf6b055f9a0c3a55abad3b0630eb2705ca59c847cdb4cc1a2e08338e9fd0cb1ae9b1000a8f5431

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
